name: cs340
version: 0.1.0.0
github: "cs340ppp/lectures"
license: MIT
author: "Michael Lee"
maintainer: "lee@iit.edu"
copyright: "2023 Michael Lee"

extra-source-files:
  - README.md
  - INSTALL.md

description: See <https://github.com/cs340ppp/lectures#readme>

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - array
  - async
  - bytestring
  - containers
  - deepseq
  - hspec
  - HUnit
  - HUnit-approx
  - memoize
  - QuickCheck
  - random
  - random-shuffle
  - split
  - stm
  - test-invariant
  - text
  - transformers

ghc-options: []

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_cs340

executables:
  app:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cs340

tests:
  cs340-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cs340
